# Generated by Django 3.2.9 on 2021-11-25 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('Acknowledgement sent', 'Acknowledgement sent'), ('Case rejected', 'Case rejected'), ('Interim report sent', 'Interim report sent'), ('Allocated to SRC Department', 'Allocated to SRC Department'), ('Allocated to Third Party', 'Allocated to Third Party'), ('Partial / Interim Response sent', 'Partial / Interim Response sent'), ('Final Response sent', 'Final Response sent'), ('Partial / Interim Response Received', 'Partial / Interim Response Received'), ('Final Response Received', 'Final Response Received'), ('Case Finalised', 'Case Finalised')], default='Request for Information', max_length=40)),
                ('query', models.CharField(choices=[('Request for Information', 'Request for Information'), ('Automatic Exchange of Information', 'Automatic Exchange of Information'), ('Spontaneous Exchange of Information', 'Spontaneous Exchange of Information')], default='Request for Information', max_length=150)),
                ('requesting_party_reference_number', models.CharField(default='', max_length=20)),
                ('last_updated', models.DateTimeField(default='2021-11-12 06:00:00.000000-08:00', editable=False)),
                ('case_age', models.DurationField(blank=True, null=True)),
                ('date_received', models.DateField(default='2021-11-12')),
                ('date_created', models.DateTimeField(default='2021-11-12 06:00:00.000000-08:00', editable=False)),
                ('legal_instrument', models.CharField(default='', max_length=20)),
                ('point_of_contact_name', models.CharField(default='', max_length=20)),
                ('point_of_contact_surname', models.CharField(default='', max_length=20)),
                ('point_of_contact_title', models.CharField(default='', max_length=20)),
                ('point_of_contact_email', models.EmailField(default='', max_length=254)),
                ('point_of_contact_telephone1', models.IntegerField(blank=True, default='0123430000')),
                ('point_of_contact_telephone2', models.IntegerField(blank=True, default='0123430001')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=30, unique=True)),
                ('subject', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(default='', max_length=4000)),
                ('created_at', models.DateTimeField(default='2021-11-12 06:00:00.000000-08:00', editable=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='outwards.case')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='outward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='outwards.outward'),
        ),
    ]
