# Generated by Django 3.2.8 on 2021-12-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outwards', '0007_alter_outward_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outward',
            name='reference',
            field=models.CharField(default='SRC.I.', max_length=12, unique=True),
        ),
    ]
