# Generated by Django 3.2.8 on 2021-12-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outwards', '0008_alter_outward_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
