# Generated by Django 3.2.8 on 2021-12-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outwards', '0010_alter_case_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_received',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
