# Generated by Django 3.2.8 on 2022-02-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outwards', '0012_auto_20220127_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='deadline',
            field=models.CharField(choices=[('Acknowledgement sent', '3 days'), ('Case rejected', '60 days'), ('Interim report sent', '90 days'), ('Allocated to SRC Department', '120 days'), ('Allocated to Third Party', '180 days'), ('Partial / Interim Response sent', '240 days'), ('Allocated to SRC Department', '360 days')], default='Acknowledgement sent', max_length=35),
        ),
    ]
