# Generated by Django 3.2.8 on 2022-02-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outwards', '0015_auto_20220209_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='deadline',
            new_name='span',
        ),
    ]
