# Generated by Django 3.2.8 on 2022-02-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outwards', '0023_alter_case_date_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='nature_of_information',
            new_name='nature_of_information_received',
        ),
        migrations.AddField(
            model_name='case',
            name='nature_of_information_requested',
            field=models.CharField(choices=[('Bank', 'Bank'), ('BO', 'BO'), ('Directors', 'Directors'), ('Accounting', 'Accounting'), ('Invoices', 'Invoices'), ('Agreements', 'Agreements'), ('Contracts', 'Contracts'), ('Others', 'Others')], default='Bank', max_length=30),
        ),
    ]
