# Generated by Django 3.2.8 on 2022-02-23 05:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outwards', '0026_alter_outward_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outward',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
