# Generated by Django 3.2.8 on 2022-04-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outwards', '0028_auto_20220302_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='taxpayer_status',
            field=models.CharField(choices=[('Not Registered', 'Not Registered'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('In Good Standing', 'In Good Standing'), ('Non-Compliant', 'Non-Compliant'), ('Struck Off', 'Struck Off'), ('Dissolved', 'Dissolved'), ('Partial / Interim Response Received', 'Not Applicable')], default='Bank', max_length=40),
        ),
    ]
