# Generated by Django 3.2.8 on 2022-04-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outwards', '0029_alter_case_taxpayer_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='point_of_contact_surname',
            new_name='others',
        ),
        migrations.RemoveField(
            model_name='case',
            name='point_of_contact_title',
        ),
        migrations.AddField(
            model_name='case',
            name='total',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outward',
            name='employee',
            field=models.CharField(choices=[('admin130', 'admin130'), ('deziburume@gmail.com', 'deziburume@gmail.com'), ('rcterblanche@gmail.com', 'rcterblanche@gmail.com')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='outward',
            name='end_date',
            field=models.DateField(default='2020-12-31'),
        ),
        migrations.AddField(
            model_name='outward',
            name='if_other',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AddField(
            model_name='outward',
            name='start_date',
            field=models.DateField(default='2015-12-12'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='tax_period',
            field=models.CharField(choices=[('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('Custom', 'Custom')], default='', max_length=15),
        ),
    ]
