# Generated by Django 3.2.9 on 2021-11-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='description',
        ),
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='message',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
        migrations.AddField(
            model_name='board',
            name='reference',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='board',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='notes',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='topic',
            name='case_age',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='date_created',
            field=models.DateTimeField(default='2021-11-12 06:00:00.000000-08:00', editable=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='date_received',
            field=models.DateField(default='2021-11-12'),
        ),
        migrations.AddField(
            model_name='topic',
            name='legal_instrument',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='point_of_contact_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='topic',
            name='point_of_contact_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='point_of_contact_surname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='point_of_contact_telephone1',
            field=models.IntegerField(blank=True, default='0123430000'),
        ),
        migrations.AddField(
            model_name='topic',
            name='point_of_contact_telephone2',
            field=models.IntegerField(blank=True, default='0123430001'),
        ),
        migrations.AddField(
            model_name='topic',
            name='point_of_contact_title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='progress',
            field=models.CharField(choices=[('Acknowledgement sent', 'Acknowledgement sent'), ('Case rejected', 'Case rejected'), ('Interim report sent', 'Interim report sent'), ('Allocated to SRC Department', 'Allocated to SRC Department'), ('Allocated to Third Party', 'Allocated to Third Party'), ('Partial / Interim Response sent', 'Partial / Interim Response sent'), ('Final Response sent', 'Final Response sent'), ('Partial / Interim Response Received', 'Partial / Interim Response Received'), ('Final Response Received', 'Final Response Received'), ('Case Finalised', 'Case Finalised')], default='Request for Information', max_length=40),
        ),
        migrations.AddField(
            model_name='topic',
            name='query',
            field=models.CharField(choices=[('Request for Information', 'Request for Information'), ('Automatic Exchange of Information', 'Automatic Exchange of Information'), ('Spontaneous Exchange of Information', 'Spontaneous Exchange of Information')], default='Request for Information', max_length=150),
        ),
        migrations.AddField(
            model_name='topic',
            name='requesting_party_reference_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default='2021-11-12 06:00:00.000000-08:00', editable=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_updated',
            field=models.DateTimeField(default='2021-11-12 06:00:00.000000-08:00', editable=False),
        ),
    ]
