# Generated by Django 3.2.8 on 2021-12-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_board_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='query',
            field=models.CharField(choices=[('Request for Information', 'Request for Information'), ('Automatic Exchange of Information', 'Automatic Exchange of Information'), ('Spontaneous Exchange of Information', 'Spontaneous Exchange of Information'), ('Tax Examination Abroad', 'Tax Examination Abroad'), ('Joint Audit', 'Joint Audit'), ('Industry Wide Exchange of Information', 'Industry Wide Exchange of Information')], default='Request for Information', max_length=150),
        ),
    ]
