# Generated by Django 3.2.8 on 2021-12-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_alter_board_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_received',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
