# Generated by Django 3.2.8 on 2022-02-10 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_rename_deadline_topic_span'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='date_closed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
