# Generated by Django 3.2.8 on 2022-02-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_inwardrequestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.DeleteModel(
            name='InwardRequestModel',
        ),
    ]
