# Generated by Django 3.2.8 on 2022-02-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_auto_20220214_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tax_period',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=15),
        ),
    ]
