# Generated by Django 3.2.8 on 2022-02-17 10:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0022_auto_20220215_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='country',
            field=django_countries.fields.CountryField(default='ZA', max_length=2),
        ),
    ]
