# Generated by Django 3.2.8 on 2022-02-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_auto_20220223_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date_closed',
            new_name='date_process_finished',
        ),
    ]
