# Generated by Django 3.2.8 on 2022-02-23 06:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0026_rename_date_closed_topic_date_process_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
