# Generated by Django 3.2.8 on 2022-02-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0027_alter_board_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='total',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
