# Generated by Django 3.2.8 on 2022-02-25 07:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0028_topic_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='nature_of_information_received',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bank', 'Bank'), ('BO', 'BO'), ('Directors', 'Directors'), ('Accounting', 'Accounting'), ('Invoices', 'Invoices'), ('Agreements', 'Agreements'), ('Contracts', 'Contracts'), ('Others', 'Others')], max_length=65),
        ),
        migrations.AlterField(
            model_name='topic',
            name='nature_of_information_requested',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bank', 'Bank'), ('BO', 'BO'), ('Directors', 'Directors'), ('Accounting', 'Accounting'), ('Invoices', 'Invoices'), ('Agreements', 'Agreements'), ('Contracts', 'Contracts'), ('Others', 'Others')], max_length=65),
        ),
    ]
