# Generated by Django 3.2.8 on 2022-03-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0029_auto_20220225_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='span',
            new_name='time_to_completion',
        ),
    ]
