# Generated by Django 3.2.8 on 2022-04-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0030_rename_span_topic_time_to_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tax_period',
            field=models.CharField(choices=[('Today', 'Today'), ('Yesterday', 'Yesterday'), ('Last 7 Days', 'Last 7 Days'), ('Last 14 Days', 'Last 14 Days'), ('Last 30 Days', 'Last 30 Days'), ('Last 60 Days', 'Last 60 Days'), ('Last 90 Days', 'Last 90 Days'), ('This Year', 'This Year'), ('All Time', 'All Time'), ('Custom', 'Custom')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='topic',
            name='taxpayer_status',
            field=models.CharField(choices=[('Not Registered', 'Not Registered'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('In Good Standing', 'In Good Standing'), ('Non-Compliant', 'Non-Compliant'), ('Struck Off', 'Struck Off'), ('Dissolved', 'Dissolved'), ('Partial / Interim Response Received', 'Not Applicable')], default='Bank', max_length=40),
        ),
    ]
