# Generated by Django 3.2.8 on 2022-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0031_auto_20220426_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='end_date',
            field=models.DateField(default='2020-12-31'),
        ),
        migrations.AddField(
            model_name='board',
            name='start_date',
            field=models.DateField(default='2015-12-12'),
        ),
    ]
