# Generated by Django 3.2.8 on 2022-04-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0034_auto_20220427_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='employee',
            field=models.CharField(choices=[('admin130', 'admin130'), ('deziburume@gmail.com', 'deziburume@gmail.com'), ('rcterblanche@gmail.com', 'rcterblanche@gmail.com')], default='', max_length=100),
        ),
    ]
