# Generated by Django 3.2.8 on 2022-04-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0035_board_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='if_other',
            field=models.CharField(default='n/a', max_length=50),
        ),
    ]
