# Generated by Django 3.2.8 on 2022-06-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0036_alter_board_if_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='point_of_contact_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
