# Generated by Django 3.2.8 on 2022-06-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0038_alter_topic_point_of_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='point_of_contact_telephone1',
            field=models.CharField(blank=True, default='0123430000', max_length=150),
        ),
    ]
