# Generated by Django 3.2.8 on 2022-06-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0039_alter_topic_point_of_contact_telephone1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='point_of_contact_telephone2',
            field=models.IntegerField(blank=True, default='0123430001', max_length=150),
        ),
    ]
